name: Build titanic model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.10]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${matrix.python-version}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r project_with_test/requirements/test_requirements.txt

    - name: Build model
      run: |
        python project_with_test/titanic_model/train_pipeline.py

    - name: Run tests
      run: |
        pytest

    - name: Upload model
      if: false
      uses: actions/upload-artifact@v2
      with:
        name: model
        path: project_with_test/model.pkl


