name: Build titanic model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${matrix.python-version}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r project_with_test/requirements/test_requirements.txt

    - name: Build model
      run: |
        python project_with_test/titanic_model/train_pipeline.py

    - name: Run tests
      run: |
        pytest
    
    - name: Install build
      run: |
        pip install build

    - name: Build the package
      run: |
        python -m build

    - name: Upload the wheel file for the trained model
      uses: actions/upload-pages-artifact@v3
      with:
        name: titanic_model
        path: project_with_test/dist/titanic_model-0.0.1-py3-none-any.whl


